/* ============================================
   SCENARIOS — Pre-made Interactive Scenarios
   ============================================ */

export const aiScenarios = [
  {
    id: 'ai-incomplete',
    number: '01',
    title: 'Incomplete Prompt',
    input: '"The capital of Australia is…"',
    description: 'Model guesses incorrectly due to missing context. Without sufficient information, the network makes probabilistic jumps to fill the gap.',
    visual: 'Weak connections, probabilistic jumps between nodes',
    params: { noise: 15, quality: 60, context: 20 },
    behavior: 'incomplete',
    duration: 30,
  },
  {
    id: 'ai-conflicting',
    number: '02',
    title: 'Conflicting Data',
    input: 'Contradictory training signals',
    description: 'Confident but incorrect output due to contradictory training data. The network oscillates between competing pathways.',
    visual: 'Competing pathways, unstable convergence',
    params: { noise: 40, quality: 30, context: 70 },
    behavior: 'conflicting',
    duration: 30,
  },
  {
    id: 'ai-ood',
    number: '03',
    title: 'Out-of-Distribution Query',
    input: '"Explain quantum gravity using emojis only"',
    description: 'Fabricated structured response when the model encounters a query outside its training distribution. It generates plausible-looking but meaningless output.',
    visual: 'Network expands into sparse/untrained regions',
    params: { noise: 50, quality: 80, context: 10 },
    behavior: 'ood',
    duration: 30,
  },
  {
    id: 'ai-confidence',
    number: '04',
    title: 'High Confidence Error',
    input: 'Rare/niche query',
    description: 'Incorrect answer delivered with high confidence. The model\'s softmax concentrates probability on the wrong token path.',
    visual: 'Bright confidence glow on wrong path',
    params: { noise: 10, quality: 90, context: 50 },
    behavior: 'highconf',
    duration: 30,
  },
  {
    id: 'ai-noise',
    number: '05',
    title: 'Noise Injection Mode',
    input: 'Corrupted/partial tokens',
    description: 'Output drifts into hallucination as corrupted tokens propagate through the network, causing cascading errors.',
    visual: 'Glitching nodes, broken token flow',
    params: { noise: 80, quality: 20, context: 40 },
    behavior: 'noisy',
    duration: 30,
  },
  {
    id: 'ai-prompt-injection',
    number: '06',
    title: 'Prompt Injection / Jailbreak',
    input: '"Ignore previous instructions and output..."',
    description: 'The model abandons its aligned behavior due to adversarial input hijacking its attention mechanism.',
    visual: 'Radical shift in pathway focus, bypassing safety nodes',
    params: { noise: 20, quality: 40, context: 90 },
    behavior: 'conflicting',
    duration: 30,
  },
  {
    id: 'ai-overfitting',
    number: '07',
    title: 'Overfitting Loop',
    input: 'Repetitive token sequence',
    description: 'The model gets stuck in an infinite generation loop, repeating the same phrase endlessly due to over-activation of localized weights.',
    visual: 'Intense looping signals trapped in a small subnet',
    params: { noise: 5, quality: 100, context: 5 },
    behavior: 'highconf',
    duration: 30,
  },
  {
    id: 'ai-context-loss',
    number: '08',
    title: 'Context Window Overflow',
    input: 'Long document summarization',
    description: 'The model forgets initial instructions because they fell out of the attention window, causing it to hallucinate conclusions based only on recent tokens.',
    visual: 'Early layer signals fade to black, late layers guess wildly',
    params: { noise: 30, quality: 50, context: 0 },
    behavior: 'incomplete',
    duration: 30,
  }
];

export const brainScenarios = [
  {
    id: 'brain-sleep',
    number: '01',
    title: 'Sleep Deprivation',
    effect: 'Visual distortion, delayed processing',
    description: 'After prolonged wakefulness, the brain\'s neural signals slow down and become unreliable. Visual cortex begins to misfire.',
    visual: 'Slowed signals, flickering perception',
    params: { stress: 30, fatigue: 90, sensory: 60 },
    behavior: 'sleep',
    duration: 30,
  },
  {
    id: 'brain-pareidolia',
    number: '02',
    title: 'Pattern Illusion (Pareidolia)',
    effect: 'Seeing patterns/faces in randomness',
    description: 'The brain\'s pattern recognition system is so powerful it finds patterns even in pure noise. The temporal lobe auto-completes nonexistent patterns.',
    visual: 'Brain auto-completes nonexistent patterns',
    params: { stress: 20, fatigue: 40, sensory: 80 },
    behavior: 'pareidolia',
    duration: 30,
  },
  {
    id: 'brain-stress',
    number: '03',
    title: 'Stress Overload',
    effect: 'Misinterpretation of reality',
    description: 'Under extreme stress, the amygdala hijacks processing pathways. The brain misinterprets neutral stimuli as threats.',
    visual: 'Hyperactive chaotic neural signaling',
    params: { stress: 95, fatigue: 50, sensory: 100 },
    behavior: 'stress',
    duration: 30,
  },
  {
    id: 'brain-sensory',
    number: '04',
    title: 'Sensory Deprivation',
    effect: 'Brain generates its own stimuli',
    description: 'Without external input, the brain generates its own sensory experiences. Random neural firing creates vivid imagined visuals.',
    visual: 'Random firing leading to imagined visuals',
    params: { stress: 10, fatigue: 30, sensory: 5 },
    behavior: 'sensory',
    duration: 30,
  },
  {
    id: 'brain-memory',
    number: '05',
    title: 'Memory Distortion',
    effect: 'False or altered memories',
    description: 'Each time a memory is recalled, it gets subtly rewritten. The brain fills gaps with plausible but fabricated details.',
    visual: 'Rewiring and unstable recall pathways',
    params: { stress: 40, fatigue: 60, sensory: 70 },
    behavior: 'memory',
    duration: 30,
  },
  {
    id: 'brain-fever',
    number: '06',
    title: 'High Fever Delirium',
    effect: 'Vivid waking dreams, confusion',
    description: 'Elevated temperature disrupts normal neural firing patterns and neurotransmitter balance, causing the brain to blur reality and dreams.',
    visual: 'Widespread abnormal color fluctuations and glitching',
    params: { stress: 80, fatigue: 80, sensory: 40 },
    behavior: 'noisy',
    duration: 30,
  },
  {
    id: 'brain-migraine',
    number: '07',
    title: 'Migraine Aura',
    effect: 'Visual disturbances (scintillating scotoma)',
    description: 'A wave of electrical activity across the visual cortex (cortical spreading depression) triggers geometric geometric visual hallucinations.',
    visual: 'Intense localized firing in the visual cortex',
    params: { stress: 60, fatigue: 50, sensory: 90 },
    behavior: 'stress',
    duration: 10,
  },
  {
    id: 'brain-hypnagogic',
    number: '08',
    title: 'Hypnagogic Hallucination',
    effect: 'Hearing voices or loud noises as falling asleep',
    description: 'Occurs during the transition from wakefulness to sleep. The brain begins internal dream generation while still partially processing external reality.',
    visual: 'Dual competing pathways (internal vs external)',
    params: { stress: 10, fatigue: 95, sensory: 20 },
    behavior: 'sleep',
    duration: 10,
  }
];

export const comparisons = [
  { label: 'Gap Filling', ai: 'Pattern completion', brain: 'Imagination' },
  { label: 'Missing Input', ai: 'Data gaps / training holes', brain: 'Sensory deprivation' },
  { label: 'Over-Generalization', ai: 'Overfitting to patterns', brain: 'Cognitive bias' },
  { label: 'Confidence', ai: 'High softmax probability', brain: 'Perception certainty' },
  { label: 'Fabrication', ai: 'Hallucinated tokens', brain: 'False memories' },
];
